mysql:
  username: root
  password: root
  database: datafabric
  port: 3306
  image: 192.168.179.18/datafabric/datafabric_mysql:20241212_v1
  resources:
    requests:
      cpu: 2
      memory: 2G
    limits:
      cpu: 2
      memory: 2G
  volume:
    size: 1G


